#!/bin/bash
# Quick Fix Steps for 404 Error

echo "🔧 Fixing 404 Error for Company Images Upload"
echo "=============================================="
echo ""
echo "Step 1: KILL existing server process"
echo "  - Open the terminal running 'npm start' in server folder"
echo "  - Press Ctrl+C to stop it"
echo ""
echo "Step 2: CLEAR Node cache"
echo "  Run in server directory:"
echo "  rm -rf node_modules/.cache"
echo ""
echo "Step 3: RESTART the server"
echo "  Run in server directory:"
echo "  npm start"
echo ""
echo "Step 4: VERIFY the endpoint is running"
echo "  Open browser and go to:"
echo "  http://localhost:4000/api/company"
echo "  Should see company data with image fields"
echo ""
echo "Step 5: TEST the upload"
echo "  Go back to Admin Dashboard Settings tab"
echo "  Try uploading an image again"
echo "  Should see success message"
echo ""
echo "✅ If above doesn't work, run the verification script:"
echo "  node VERIFY_SETUP.js"
